### ISSUE TITLE
Nice Malware!

### ISSUE THREAD

**Issue by Cristian1520** [the-the-1/bloxstrap-with-multi-instance-launching#1]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

Latest

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/32d093ef-f7c2-401a-aaeb-ccfc57eddda7)
**Malware..** Why tho does hacking people computers make you happy does it bring a smile to your face? 

### Bloxstrap Log

```text
N/A
```

**Comment by Cristian1520** [comment]
If You want to see what it does heres the triage link!
https://tria.ge/241214-ml8cnsypgx

**Comment by the-the-1** [comment]
it's not malware, you can literally check the source code to see

**Comment by Cristian1520** [comment]
> it's not malware, you can literally check the source code to see
Then Why does triage say it is because when i try normal bloxstrap it says its a 1/10
